# BoxpvpRooms Configuration File
# Advanced Rooms and Betting System for PvP battles
# Transform your server into the best PvP experience!

# Default settings for new arenas
default-arena-settings:
  # The material used for the arena's boundary walls (e.g., GLASS, BEDROCK, IRON_BARS).
  # Use exact Minecraft material names (e.g., OAK_PLANKS, STONE, BARRIER).
  wall-material: "GLASS"

  # Block interaction settings
  allow-block-break: false     # Allow players to break blocks inside arena
  allow-block-place: false     # Allow players to place blocks inside arena
  allow-item-drop: false       # Allow players to drop items inside arena

  # Enhanced BoxpvpRooms settings
  keep-inventory: false        # Keep inventory on death (per arena configurable)
  combat-log: true            # Prevent logout during combat
  prevent-blocks: true        # Prevent block placement/breaking (unified setting)

  # Game mechanics
  disable-hunger: true        # Disable hunger depletion inside arena
  wall-removal-delay-seconds: 30  # Delay before walls disappear after combat

  # Default potion effects applied to players when entering arena
  # Format: "EFFECT_NAME:AMPLIFIER" (e.g., "SPEED:1" for Speed II, "JUMP_BOOST:2" for Jump Boost III)
  # Amplifier is 0-indexed (0 for level I, 1 for level II, etc.)
  effects: []

  # Number of players required to activate arena (2 for 1v1, 4 for 2v2, etc.)
  required-players: 2

# Statistics and Database Configuration
statistics:
  # Enable statistics tracking (requires SQLite)
  enabled: true

  # Database settings
  database:
    # SQLite database file name (stored in plugin folder)
    filename: "database.db"

    # Enable database backup on startup
    backup-on-startup: true

    # Cleanup old match records (days, 0 = never)
    cleanup-old-matches: 365

# Betting System Configuration
betting:
  # Enable the revolutionary betting system
  enabled: true

  # Minimum bet value (for item-based betting)
  min-bet-value: 1

  # Maximum bet value (for item-based betting)
  max-bet-value: 64

  # Allow betting on yourself (not recommended for fairness)
  allow-self-betting: false

  # Betting timeout in seconds (auto-close betting before match starts)
  betting-timeout: 30

  # Visual effects for winners
  winner-effects:
    fireworks: true
    sounds: true
    titles: true

# Room Type Specific Settings
room-types:
  normal:
    display-name: "Normal PvP"
    description: "Classic 1v1 combat rooms"
    default-size: 2

  team:
    display-name: "Team Battle"
    description: "Team battles with intelligent auto-assignment"
    default-size: 4
    auto-balance: true
    friendly-fire: false

  clan:
    display-name: "Clan Wars"
    description: "Organized duels between clans"
    default-size: 4
    require-clan-membership: true
    friendly-fire: false

# Message configuration
messages:
  # Enable fancy Unicode text styling (ᴛʜɪѕ ɪѕ ᴇхᴀᴍᴘʟᴇ text)
  use-fancy-unicode: true

  # Prefix for all plugin messages
  prefix: "&6[&eBoxpvpRooms&6]&r "

  # Game messages
  arena-sealed: "&aThe arena has been sealed! Fight!"
  arena-wall-removed: "&cThe arena wall has been removed."
  arena-wall-removal-countdown: "&eThe arena wall will be removed in &c{delay} &eseconds."
  arena-opens-countdown: "&bArena opens in &a{seconds} &bseconds"

  # Match messages
  match-started: "&a▬▬▬ &lMATCH STARTED &a▬▬▬"
  match-ended: "&c▬▬▬ &lMATCH ENDED &c▬▬▬"
  player-won: "&a{winner} &ewon against &c{loser}&e!"
  player-eliminated: "&c{player} &ehas been eliminated!"

  # Team messages
  team-assigned: "&aYou have been assigned to &l{team} &ateam!"
  team-balanced: "&eTeams have been automatically balanced."
  waiting-for-players: "&eWaiting for more players... &7({current}/{required})"

  # Selection tool messages
  selection-wand-name: "&6&lBoxpvpRooms Selection Wand"
  selection-wand-received: "&aYou have received the selection wand!"
  selection-mode-changed: "&aSelection mode changed to: &e{mode}"

  # Arena management messages
  arena-created: "&aArena &e'{name}' &ahas been created successfully!"
  arena-deleted: "&cArena &e'{name}' &chas been deleted."
  arena-not-found: "&cArena &e'{name}' &cnot found."
  arena-saved: "&aArena &e'{name}' &asaved successfully!"

  # Property messages
  property-updated: "&aProperty &e{property} &aset to &e{value} &afor arena &e{arena}"
  invalid-property: "&cInvalid property! Available: keepinventory, combatlog, preventblocks, barrier, effect"
  invalid-material: "&cInvalid material: &e{material}"

  # Statistics messages
  stats-header: "&6&l▬▬▬ &e{player}'s Statistics &6&l▬▬▬"
  stats-kills: "&aKills: &f{kills}"
  stats-deaths: "&cDeaths: &f{deaths}"
  stats-wins: "&2Wins: &f{wins}"
  stats-losses: "&4Losses: &f{losses}"
  stats-kdr: "&eK/D Ratio: &f{kdr}"
  stats-winrate: "&bWin Rate: &f{winrate}%"

  # Leaderboard messages
  leaderboard-header: "&6&l▬▬▬ &eTop {category} &6&l▬▬▬"
  leaderboard-entry: "&e#{rank} &f{player} &7- &a{value}"

  # Command messages
  no-permission: "&cYou don't have permission to use this command."
  player-only: "&cThis command can only be used by players."
  invalid-usage: "&cInvalid usage. Use: &e{usage}"
  command-disabled: "&cThis feature is currently disabled."

  # Betting messages
  bet-placed: "&aYou bet &e{amount} &aon &e{target}&a!"
  bet-won: "&a&lYOU WON! &aYour bet paid out &e{amount}&a!"
  bet-lost: "&c&lYOU LOST! &cBetter luck next time."
  bet-refunded: "&eYour bet has been refunded due to match cancellation."
  betting-closed: "&cBetting is now closed for this match."
  invalid-bet: "&cInvalid bet amount or target."

# Arena-specific settings for block replacement
arena-settings:
  # Materials that can be safely replaced by arena walls
  # Only these blocks will be replaced when walls are built
  # Solid blocks should NOT be in this list to prevent griefing
  replaceable-materials:
    - AIR
    - CAVE_AIR
    - VOID_AIR
    - WATER
    - LAVA
    - FLOWING_WATER
    - FLOWING_LAVA
    - TALL_GRASS
    - SEAGRASS
    - VINE
    - TORCH
    - WALL_TORCH
    - SOUL_TORCH
    - SOUL_WALL_TORCH
    - REDSTONE_TORCH
    - REDSTONE_WALL_TORCH
    - REDSTONE_WIRE
    - FIRE
    - SOUL_FIRE
    - SNOW
    - COBWEB
    - SUGAR_CANE
    - WHEAT
    - CARROTS
    - POTATOES
    - BEETROOTS
    - NETHER_WART
    - LADDER
    - LEVER
    - STONE_BUTTON
    - OAK_BUTTON
    - SPRUCE_BUTTON
    - BIRCH_BUTTON
    - JUNGLE_BUTTON
    - ACACIA_BUTTON
    - DARK_OAK_BUTTON
    - CRIMSON_BUTTON
    - WARPED_BUTTON
    - POLISHED_BLACKSTONE_BUTTON
    - BROWN_MUSHROOM
    - RED_MUSHROOM
    - DEAD_BUSH
    - FERN
    - LARGE_FERN
    - FLOWER_POT
    - OAK_SAPLING
    - SPRUCE_SAPLING
    - BIRCH_SAPLING
    - JUNGLE_SAPLING
    - ACACIA_SAPLING
    - DARK_OAK_SAPLING
    - CRIMSON_FUNGUS
    - WARPED_FUNGUS
    - DANDELION
    - POPPY
    - BLUE_ORCHID
    - ALLIUM
    - AZURE_BLUET
    - RED_TULIP
    - ORANGE_TULIP
    - WHITE_TULIP
    - PINK_TULIP
    - OXEYE_DAISY
    - CORNFLOWER
    - LILY_OF_THE_VALLEY
    - WITHER_ROSE
    - SUNFLOWER
    - LILAC
    - ROSE_BUSH
    - PEONY
    - TRIPWIRE_HOOK
    - TRIPWIRE
    - STRING

  # Maximum arena size (prevents server lag from huge arenas)
  max-arena-size:
    x: 200
    y: 50
    z: 200

  # Minimum arena size (prevents tiny unusable arenas)
  min-arena-size:
    x: 5
    y: 3
    z: 5

# Plugin Integration Settings
integrations:
  # PlaceholderAPI integration
  placeholderapi:
    enabled: true

  # Vault economy integration (for monetary betting)
  vault:
    enabled: true

  # UltimateClans integration (for clan battles)
  ultimateclans:
    enabled: true

  # DeluxeCombat integration
  deluxecombat:
    enabled: false

  # PvPManager integration
  pvpmanager:
    enabled: false

# Performance Settings
performance:
  # Enable async database operations
  async-database: true

  # Cache player statistics (reduces database queries)
  cache-stats: true

  # Cache duration in minutes
  cache-duration: 10

  # Maximum concurrent matches
  max-concurrent-matches: 50

# Debug and Logging
debug:
  # Enable debug mode (verbose logging)
  enabled: false

  # Log database queries
  log-database-queries: false

  # Log player movements in arenas
  log-player-movements: false

# Version info (do not modify)
config-version: 1
plugin-version: "1.0"

# Arena storage (managed automatically by plugin)
arenas: {}