name: BoxpvpRooms
main: com.vypnito.boxpvprooms.BoxpvpRooms
version: 1.0
api-version: '1.17'
author: Vypnito
description: Advanced Rooms and Betting System for PvP battles with statistics and team management.
softdepend: [PlaceholderAPI, Vault]
commands:
  rooms:
    description: "Main command for BoxpvpRooms system."
    usage: "/rooms <subcommand>"
    aliases: [1v1rooms, bpr]
    permission: zoneplugin.use
permissions:
  zoneplugin.admin:
    description: "Full plugin access"
    default: op
    children:
      - zoneplugin.staff
      - zoneplugin.create
      - zoneplugin.use
      - zoneplugin.bet
      - zoneplugin.stats
  zoneplugin.staff:
    description: "Room limits bypass"
    default: op
    children:
      - zoneplugin.create
      - zoneplugin.use
      - zoneplugin.bet
      - zoneplugin.stats
  zoneplugin.create:
    description: "Create and edit zones"
    default: op
    children:
      - zoneplugin.use
  zoneplugin.use:
    description: "Use basic commands"
    default: true
  zoneplugin.bet:
    description: "Participate in betting"
    default: true
  zoneplugin.stats:
    description: "View statistics"
    default: true