package com.vypnito.arena.player;

public enum PlayerState {
	SELECTING_POS1,
	SELECTING_POS2,
	CREATING_ARENA,
	EDITING_ARENA,
	SETTING_WALL_MATERIAL,
	SETTING_DELAY,
	SETTING_CUSTOM_REQUIRED_PLAYERS,
	IN_MATCH,
	SPECTATING,
	IDLE
}